ground_truth_dir: "data/ground_truth"
model_outputs_dir: "data/model_outputs"
evaluation:
  metrics:
    - MAE
    - MAPE
    - MRE
    - ASYMMETRIC
  format: "csv"
  output_path: "./20250214_evaluation_report"
log_file: "logs/evaluation.log"