version: '3.8'

services:
  ai_ml_evaluator:
    build: ./app
    container_name: ai_ml_evaluator
    volumes:
      - ./app/data:/app/data
      - ./app/reports:/app/reports
      - ./app/config.yaml:/app/config.yaml
    environment:
      - CONFIG_PATH=/app/config.yaml
    command: ["python", "main.py"]

  streamlit_app:
    build: ./ui
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./app/reports:/app/reports

    command: ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
