ground_truth_dir: "data/ground_truth"
model_outputs_dir: "data/model_outputs"
evaluation:
  metrics:
    - MAE
    - MAPE
    - MRE
    - ASYMMETRIC
  format: "json"
  output_path: "reports/20250214_evaluation_report"
log_file: "logs/evaluation.log"